# This is a basic workflow to help you get started with Actions

name: Pull request

# Controls when the action will run. 
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up MSBuild in PATH for command
      - name: Setup MSBuild in PATH
        uses: microsoft/setup-msbuild@v1
        
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      # Get NuGet setup for restoring, packaging and pushing
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore packages with NuGet
        run: nuget restore Unleash.sln /p:Configuration=Release
        
      - name: Build the solution
        run: msbuild Unleash.sln
        
      - name: Run the tests
        run: '& "$(vswhere -property installationPath)\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" tests\Unleash.Tests\bin\Release\Unleash.Tests.dll'
